### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by sharadbhat** [pldubouilh/gossa-ui#13]
I noticed in your Makefile that it is copied into `../gossa.go`. Based on the assumption that `gossa-ui` repository will be a submodule in the `gossa` repository, shouldn't the path be `../src/gossa.go`?

`Makefile`
> 	perl -pe 's/template_will_be_here/`cat ui.tmpl`/ge' -i ../gossa.go
	perl -pe 's/css_will_be_here/`cat style.css`/ge' -i ../gossa.go
	perl -pe 's/js_will_be_here/`cat script.js`/ge' -i ../gossa.go
	perl -pe 's/favicon_will_be_here/`base64 -w0 favicon.png`/ge' -i ../gossa.go

If so, I can create a PR with this and other minor improvement tweaks.

**Comment by pldubouilh** [comment]
sorry for the slow reply, I didn't see your issue for some reason - yes it's a tad convoluted, the aim was to cram everything into `../gossa.go`, so that the end binary does not depend on external files.

The idea was to have `gossa/src/gossa.go` as the sourcefile, and `gossa/gossa.go` as a temporary source that's modified by this makefile to hardcode all the CSS/JS/etc depencies hardcoded into it. This file temporary bundled source is then built, and `rm`'ed.

Looking forward to hear about other minor tweaks if you still have them at hand though :)
